# Generated by Django 3.2 on 2023-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fcltdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcltName', models.CharField(max_length=250)),
                ('fcltDepartment', models.CharField(max_length=250)),
                ('fcltMailid', models.EmailField(max_length=150)),
                ('fcltphone_no', models.IntegerField(default=0)),
                ('fcltAddress', models.CharField(max_length=250)),
            ],
        ),
    ]
