# Generated by Django 3.2 on 2023-12-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcltleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=250)),
                ('leavetype', models.CharField(max_length=250)),
                ('leavestartdate', models.DateField()),
                ('leaveenddate', models.DateField()),
            ],
        ),
    ]
