# Generated by Django 3.2 on 2023-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=250)),
                ('studentid', models.CharField(max_length=250)),
                ('feeamount', models.CharField(max_length=250)),
            ],
        ),
    ]
